---
name: XML-Filter-Conditional
version: 0.04
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: |-
  an XML SAX filter for conditionally ignoring XML
  content
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  XML::SAX::Base: 0
build_requires:
  Test::Exception: 0
  Test::More: 0
  XML::SAX::ParserFactory: 1.00
provides:
  XML::Filter::Conditional:
    file: lib/XML/Filter/Conditional.pm
    version: 0.04
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
